### ISSUE TITLE
クウォートだけだとSEGV

### ISSUE THREAD

**Issue by oooooorriiiii** [oooooorriiiii/minishell#61]

**Comment by oooooorriiiii** [comment]
```sh
minishell> "
srcs/execute/execute_simple_command.c:17:7: runtime error: null pointer passed as argument 2, which is declared to never be null
AddressSanitizer:DEADLYSIGNAL
=================================================================
==9024==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f2fd627c890 bp 0x7ffd9f200bf0 sp 0x7ffd9f200350 T0)
==9024==The signal is caused by a READ memory access.
==9024==Hint: address points to the zero page.
    #0 0x7f2fd627c88f  (/lib/x86_64-linux-gnu/libasan.so.5+0xd688f)
    #1 0x55b8c8c09a13 in check_builtin srcs/execute/execute_simple_command.c:17
    #2 0x55b8c8c09be7 in execute_simple_command srcs/execute/execute_simple_command.c:31
    #3 0x55b8c8c0a4f1 in execute_command srcs/execute/execute_simple_command.c:71
    #4 0x55b8c8c0d5cc in execute_job srcs/execute/execute.c:57
    #5 0x55b8c8c0d614 in execute_cmdline srcs/execute/execute.c:66
    #6 0x55b8c8c0d674 in execute_syntax_tree srcs/execute/execute.c:77
    #7 0x55b8c8bfbc30 in minishell_loop srcs/main.c:61
    #8 0x55b8c8bfc3ef in main srcs/main.c:118
    #9 0x7f2fd561e0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #10 0x55b8c8bfb71d in _start (/home/ymori/42/minishell/minishell+0x2871d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libasan.so.5+0xd688f) 
==9024==ABORTING

```
